version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - FLASK_APP='app/src/'
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .postgres_db:/var/lib/postgresql/data
    ports:
      - 5433:5432
